homebrew_taps:
  - heroku/brew
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/core
  - heroku/brew
homebrew_cask_packages:
  - name: karabiner-elements
  - name: alfred
  - name: rectangle
  - name: google-japanese-ime
  - name: google-chrome
  - name: hyper
  - name: visual-studio-code
  - name: font-hackgen
  - name: viber
  - name: toggl
  - name: postman
  # - name: phpstorm
  # - name: intellij-idea-ce
  # - name: dash
  # - name: katalon-studio
  - name: appcleaner
  - name: bartender
  - name: cyberduck
  - name: figma
  - name: firefox
  # - name: vagrant
  # - name: virtualbox
  - name: sequel-pro
  - name: the-unarchiver
  - name: charles
  - name: docker
  - name: slack
  # - name: burp-suite
  # - name: box-drive
  # - name: box-notes
  # - name: microsoft-teams
  # - name: microsoft-office
  # - name: zoomus
  # - name: ngrok
  # - name: skitch
  # - name: bitwarden
homebrew_packages:
  - name: ansible
  - name: git
  - name: hub
  - name: ghq
  - name: peco
  - name: fish
  - name: fzf
  - name: vim
  - name: ripgrep
  - name: tig
  - name: tree
  - name: tmux
  - name: awscli
  - name: bash-completion
  - name: jq
  - name: mas
  - name: wget
  - name: anyenv
  - name: nkf
  - name: hugo
  - name: q
  - name: yarn
  - name: gnu-sed
  - name: colordiff
  # - name: docker
  # - name: heroku
  # - name: bitwarden-cli
  # - name: terraform
  # - name: tfenv
dot_files:
  - name: .bash_profile
  - name: .bashrc
  - name: .tmux.conf
  - name: .vimrc
  - name: .gitconfig
  - name: .gitattributes
  - name: .gitignore_global
  - name: .hyper.js
  - name: .config
