homebrew_taps:
  - heroku/brew
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/core
  - heroku/brew
homebrew_cask_packages:
  - name: alfred
  - name: appcleaner
  - name: bartender
  - name: bitwarden
  - name: box-drive
  - name: clipy
  - name: cyberduck
  - name: docker
  - name: drawio
  - name: figma
  - name: firefox
  - name: google-chrome
  - name: google-japanese-ime
  - name: hyper
  - name: hyperswitch
  - name: hugo
  - name: karabiner-elements
  # - name: microsoft-teams
  # - name: microsoft-office
  - name: ngrok
  - name: notable
  - name: postman
  - name: sequel-pro
  - name: skitch
  - name: rectangle
  # - name: spectacle
  - name: toggl
  # - name: slack
  - name: vagrant
  - name: virtualbox
  - name: visual-studio-code
  - name: viber
  - name: java
  - name: jmeter
  #- name: phpstorm
  # - name: zoomus
  - name: font-hackgen
homebrew_packages:
  - name: ansible
  - name: awscli
  - name: bash-completion
  - name: bitwarden-cli
  - name: docker
  - name: fish
  - name: fzf
  - name: git
  - name: heroku
  - name: hub
  - name: jq
  - name: mas
  - name: ghq
  - name: peco
  # - name: terraform
  - name: tfenv
  - name: tig
  - name: tree
  - name: tmux
  - name: vim
  - name: wget
  - name: anyenv
  - name: git-lfs
dot_files:
  - name: .bash_profile
  - name: .bashrc
  - name: .tmux.conf
  - name: .vimrc
  - name: .gitconfig
  - name: .gitattributes
  - name: .gitignore_global
  - name: .hyper.js

