- block:

  - name: 設定ファイルのバックアップ
    shell: 'defaults read > before_defaults'

  - name: キーリピート検知待ち時間
    osx_defaults:
      key: InitialKeyRepeat
      type: int
      value: 15
      state: present

  - name: キーリピート間隔時間
    osx_defaults:
      key: KeyRepeat
      type: int
      value: 2
      state: present

  - name: Dock autohide
    osx_defaults:
      domain: com.apple.dock
      key: autohide
      type: bool
      value: true
      state: present

  - name: バッテリー残量設定 # macOS 11以降は効かない。システム設定 > コントロールセンター > バッテリー > 割合(%)を表示 で手動ON
    osx_defaults:
      domain: com.apple.menuextra.battery
      key: ShowPercent
      type: string
      value: YES
      state: present

  - name: トラックパッドタップの有効化
    osx_defaults:
      domain: com.apple.AppleMultitouchTrackpad
      key: Clicking
      type: int
      value: 1
      state: present

  - name: "Keyboard - Full Keyboard Access (1:text , list only 3: all)"
    osx_defaults:
      domain: 'NSGlobalDomain'
      key: 'AppleKeyboardUIMode'
      type: int
      value: 3

  - name: 右下でスクリーンセーバー開始1
    osx_defaults:
      domain: com.apple.dock.plist
      key: wvous-br-corner
      type: int
      value: 5

  - name: 右下でスクリーンセーバー開始2
    osx_defaults:
      domain: com.apple.dock.plist
      key: wvous-br-modifier
      type: int
      value: 0

  - name: dock の表示内容はアクティブAPPのみ
    osx_defaults:
      domain: com.apple.dock
      key: static-only
      type: bool
      value: true

  - name: 現在の設定ファイルのバックアップ
    shell: 'defaults read > after_defaults'

  tags:
    - osx
